import 'package:core/core.dart';
import 'package:flutter/material.dart';
import 'package:models/models.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:ui_kit/ui_kit.dart';
import 'ticket_screen.dart';
import 'package:intl/intl.dart';

class EventDetailScreen extends StatefulWidget {
  final Activity activity;
  const EventDetailScreen({super.key, required this.activity});

  @override
  State<EventDetailScreen> createState() => _EventDetailScreenState();
}

class _EventDetailScreenState extends State<EventDetailScreen> {
  final _activityRepo = ActivityRepository();
  ActivityRegistration? _registration;
  bool _isLoading = true;
  bool _isRegistering = false;

  final Map<String, dynamic> _formResponses = {};

  @override
  void initState() {
    super.initState();
    _checkRegistration();
  }

  Future<void> _checkRegistration() async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user != null) {
      final reg = await _activityRepo.getUserRegistration(widget.activity.id, user.id);
      if (mounted) {
        setState(() {
          _registration = reg;
          _isLoading = false;
        });
      }
    } else {
       if (mounted) setState(() => _isLoading = false);
    }
  }

  Future<void> _register() async {
    // Validation
    final config = widget.activity.formConfig;
    if (config != null) {
       for (var field in config.fields) {
         if (field.isRequired && (_formResponses[field.id] == null || _formResponses[field.id].toString().isEmpty)) {
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('${field.label} is required.')));
            return;
         }
       }
    }

    setState(() => _isRegistering = true);
    try {
      final user = Supabase.instance.client.auth.currentUser;
      if (user == null) throw Exception("Not logged in");

      final reg = ActivityRegistration(
        id: '', // Generated by DB? No, model requires ID. Let's let DB gen it if possible or gen random here.
        // Actually our model requires ID. In createActivity we let DB gen default. 
        // Here we are inserting manual object. 
        // Best practice: Let DB handle ID, or generate UUID here.
        // Since we are using .insert(registration.toJson()), if ID is empty string it might fail if UUID check is there.
        // Let's rely on DB default if ID is excluded from JSON, BUT our model likely serializes ID.
        // Let's generate a temporary UUID if we must, or modify model to make ID optional.
        // Given current model constraint 'required this.id', let's just make a dummy or UUID.
        // Wait, 'activity_registrations' table has `id uuid default gen_random_uuid`.
        // If we want DB to gen it, we shouldn't send it. But dart model enforces it.
        // Workaround: Send a random UUID.
        activityId: widget.activity.id,
        userId: user.id,
        status: 'registered',
        formData: _formResponses,
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(), 

      );
      
      // Note: ActivityRepository.createRegistration calls .insert(registration.toJson()).
      // We need to ensure we don't send invalid UUID. 
      // Using null for ID in model would have been better for creation.
      // For now, I will create a Map manually to exclude ID so DB generates it.
      
      final Map<String, dynamic> data = {
        'activity_id': reg.activityId,
        'user_id': reg.userId,
        'status': reg.status,
        'form_data': reg.formData,
      };

      await Supabase.instance.client.from('activity_registrations').insert(data);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Registered Successfully!')));
        _checkRegistration(); // Reload to get the proper obj with ID
        setState(() => _isRegistering = false);
      }

    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error: $e')));
        setState(() => _isRegistering = false);
      }
    }
  }

  Widget _buildForm() {
    final config = widget.activity.formConfig;
    if (config == null || config.fields.isEmpty) return const SizedBox.shrink();

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text("Registration Details", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
        const SizedBox(height: 16),
        ...config.fields.map((field) {
           return Padding(
             padding: const EdgeInsets.only(bottom: 16.0),
             child: _buildFieldInput(field),
           );
        }).toList(),
      ],
    );
  }

  Widget _buildFieldInput(ActivityFormField field) {
    switch (field.type) {
      case 'dropdown':
        return DropdownButtonFormField<String>(
          decoration: InputDecoration(labelText: field.label + (field.isRequired ? ' *' : ''), border: const OutlineInputBorder()),
          items: field.options?.toSet().map((o) => DropdownMenuItem(value: o, child: Text(o))).toList(),
          onChanged: (val) => setState(() => _formResponses[field.id] = val),
        );
      case 'boolean':
        return SwitchListTile(
          title: Text(field.label + (field.isRequired ? ' *' : '')),
          value: _formResponses[field.id] == true,
          onChanged: (val) => setState(() => _formResponses[field.id] = val),
        );
      case 'date':
         // Simplified date picker
         return TextField(
           decoration: InputDecoration(labelText: field.label + (field.isRequired ? ' *' : '') + " (YYYY-MM-DD)", border: const OutlineInputBorder()),
           onChanged: (val) => _formResponses[field.id] = val,
         );
      default: // Text, number
        return TextField(
          decoration: InputDecoration(labelText: field.label + (field.isRequired ? ' *' : ''), border: const OutlineInputBorder()),
          keyboardType: field.type == 'number' ? TextInputType.number : TextInputType.text,
          onChanged: (val) => _formResponses[field.id] = val,
        );
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) return const Scaffold(body: Center(child: CircularProgressIndicator()));

    final isRegistered = _registration != null;

    return Scaffold(
      appBar: AppBar(title: const Text("Event Details")),
      body: SingleChildScrollView(
        child: Column(
          children: [
            if (widget.activity.imageUrl != null)
              Image.network(widget.activity.imageUrl!, height: 250, width: double.infinity, fit: BoxFit.cover),
            
            Padding(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(widget.activity.title, style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold)),
                  const SizedBox(height: 8),
                  Row(
                    children: [
                      const Icon(Icons.calendar_today, size: 20, color: Colors.purple),
                      const SizedBox(width: 8),
                      Text(
                        DateFormat.yMMMMEEEEd().add_Hm().format(widget.activity.startTime.toLocal()),
                        style: const TextStyle(fontSize: 16),
                      ),
                    ],
                  ),
                  if (widget.activity.location != null) ...[
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        const Icon(Icons.location_on, size: 20, color: Colors.purple),
                        const SizedBox(width: 8),
                        Text(widget.activity.location!, style: const TextStyle(fontSize: 16)),
                      ],
                    ),
                  ],
                  const SizedBox(height: 24),
                  if (widget.activity.description != null) ...[
                     Text(widget.activity.description!, style: const TextStyle(fontSize: 16)),
                     const SizedBox(height: 24),
                  ],
                  
                  const Divider(),
                  const SizedBox(height: 16),
                  
                  if (isRegistered)
                     Center(
                       child: Column(
                         children: [
                           const Icon(Icons.check_circle, color: Colors.green, size: 64),
                           const SizedBox(height: 8),
                           const Text("You are registered!", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20, color: Colors.green)),
                           const SizedBox(height: 16),
                           ElevatedButton.icon(
                             onPressed: () {
                               Navigator.push(context, MaterialPageRoute(builder: (_) => TicketScreen(
                                 activity: widget.activity, 
                                 registration: _registration!
                               )));
                             },
                             icon: const Icon(Icons.confirmation_number),
                             label: const Text("View Ticket"),
                             style: ElevatedButton.styleFrom(
                               backgroundColor: Colors.purple, 
                               foregroundColor: Colors.white,
                               padding: const EdgeInsets.symmetric(horizontal: 32, vertical: 12)
                             ),
                           )
                         ],
                       ),
                     )
                  else if (DateTime.now().isAfter(widget.activity.endTime))
                      Center(
                        child: Column(
                          children: [
                            const Icon(Icons.event_busy, color: Colors.grey, size: 64),
                            const SizedBox(height: 8),
                            const Text("Registration Closed", style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20, color: Colors.grey)),
                             const SizedBox(height: 8),
                            const Text("This event has ended.", style: TextStyle(color: Colors.grey)),
                          ],
                        ),
                      )
                  else ...[
                     _buildForm(),
                     const SizedBox(height: 24),
                     SizedBox(
                       width: double.infinity,
                       height: 50,
                       child: ElevatedButton(
                         onPressed: _isRegistering ? null : _register,
                         child: _isRegistering 
                             ? const CircularProgressIndicator() 
                             : const Text("Register Now"),
                       ),
                     ),
                  ]

                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
